#!/usr/bin/env bash
if ${DEBUG}; then
	set -x
fi

pkgs_online_repo='https://raw.githubusercontent.com/slothds/cpm-packages/master'
pkgs_local_repo="${HOME}/.local/cpm/packages"
packages_list='packages.list'

WORKDIR=$(dirname $(realpath $0))

modules="${WRKDIR}/modules.d"
functions="${WRKDIR}/functions.d"

temp_dir="/tmp/cpm"
database_dir="/var/db/cpm"

for func in ${functions}/*.func; do
    source ${func}
done

all_packages=false
run_silent=false
exec_mode=''
packages=()

if [[ -n $(which getopt) ]]; then
    parse-getopt  $@
else
    parse-getopts $@
fi

check-dir ${VERDIR} ${TMPDIR}

case ${exec_mode} in
    install) packages-install ;;
    update)  packages-update  ;;
    disable) packages-disable ;;
esac

# IFS=','
# for DIR in ${PKGDIR}; do
#     IFS=$'\r\n\t '
#     for pkg in ${DIR}/*; do
#         [[ -f ${pkg} ]] && \
#             get-package ${DIR} $(basename ${pkg}) ${RUNMODE}
#     done
# done

clean-up
